name: Deploy
on:
  push:
    branches: 
      - main
jobs:
  deploy_lambda:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: npm install and build
        env:
          CI: true
          PUPPETEER_SKIP_DOWNLOAD: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build index.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=better-health-booking-bot --zip-file=fileb://deploy.zip
          aws events put-rule --schedule-expression "cron(0 9 * * ? *)" --name "midnight-daily-cron-job"


          